#!/bin/sh

# PROVIDE: belcoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# belcoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable belcoin service.
# belcoin_config (path): Set to /usr/local/etc/belcoin.conf by default.
# belcoin_user:  The user account belcoin daemon runs as. It uses 'root' user by default.
# belcoin_group: The group account belcoin daemon runs as. It uses 'wheel' group by default.
# belcoin_datadir (str): Default to "/var/db/belcoin". Base data directory.

. /etc/rc.subr

name=belcoin
rcvar=belcoin_enable

: ${belcoin_enable:=NO}
: ${belcoin_config=/usr/local/etc/belcoin.conf}
: ${belcoin_datadir=/var/db/belcoin}
: ${belcoin_user="root"}
: ${belcoin_group="wheel"}

required_files=${belcoin_config}
command=/usr/local/bin/belcoind
belcoin_chdir=${belcoin_datadir}
pidfile="${belcoin_datadir}/belcoind.pid"
stop_cmd=belcoin_stop
command_args="-conf=${belcoin_config} -datadir=${belcoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

belcoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${belcoin_datadir}
	[ $? -eq 0 ] && chown -R ${belcoin_user}:${belcoin_group} ${belcoin_datadir}
}

belcoin_prestart()
{
	if [ ! -d "${belcoin_datadir}/." ]; then
		belcoin_create_datadir || return 1
	fi
}

belcoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

belcoin_stop()
{
    belcoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${belcoin_config} -datadir=${belcoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
